### ISSUE TITLE
downloads failed in stage3 due to expired certificates 

### ISSUE THREAD

**Issue by RavikumarTulugu** [medvid/make-rootfs#4]
2 packages failed to download due to expired certtificates. pasting alternate urls here 

diff --git a/pkg/mawk.mk b/pkg/mawk.mk
index 09c5e82..649ac2f 100644
--- a/pkg/mawk.mk
+++ b/pkg/mawk.mk
@@ -5,7 +5,8 @@
 
 pkg_ver  := 1.3.4-20200120
 pkg_repo := https://github.com/ThomasDickey/mawk-snapshots
-pkg_site := https://invisible-mirror.net/archives/mawk
+#pkg_site := https://invisible-mirror.net/archives/mawk
+pkg_site := https://distfiles.macports.org/mawk/
 
 pkg_configure := $(pkg_srcdir)/configure \
        --build=$(HOST) \
diff --git a/pkg/ncurses.mk b/pkg/ncurses.mk
index 48d43f7..861c1d3 100644
--- a/pkg/ncurses.mk
+++ b/pkg/ncurses.mk
@@ -6,7 +6,8 @@
 # https://github.com/void-linux/void-packages/blob/master/srcpkgs/ncurses/template
 
 pkg_ver  := 6.2
-pkg_site := https://invisible-mirror.net/archives/ncurses
+#pkg_site := https://invisible-mirror.net/archives/ncurses
+pkg_site := https://ftp.gnu.org/gnu/ncurses/
 
 pkg_configure := $(pkg_srcdir)/configure \
        --build=$(HOST) \

**Comment by medvid** [comment]
Thanks - https://invisible-mirror.net/archives/ certificate seems to be renewed at Oct-3.

Additionally, I updated pkg/etc/ssl/cert.pem from the latest https://curl.se/ca/cacert.pem  (by running "make update-cacert") - to exclude expired DST Root CA X3:

https://github.com/medvid/make-rootfs/commit/71f345f8affa3e6f82b897c7ec1b728bc3ee4936
